version: '3.8'

services:
  frontend:
    build:
      context: ~/project/Project_2_1_1/code for diagram 1/frontend
    ports:
      - "5005:5005"
    environment:
      - BACKEND_RDS_URL=${BACKEND_RDS_URL}
      - BACKEND_REDIS_URL=${BACKEND_REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}  
    networks:
      - project-network


  beckend_rds:
    #image: your-service1-image
    build:
      context: ~/project/Project_2_1_1/code for diagram 1/backend_rds
    ports:
      - "8001:8001"
    environment:
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
     - project-network

  backend_redis:
    #image: your-service2-image
    build:
      context: ~/project/Project_2_1_1/code for diagram 1/backend_redis
    ports:
      - "8002:8002"
    environment:
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    # depends_on:
    #  - backend_rds
    networks:
     - project-network
    
  db_postgres:
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    environment:
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    build:
      context: ~/project/Project_2_1_1/code for diagram 1/postgres
    ports:
      - "5432:5432"
    networks:
      - project-network

  db_redis:
    image: redis:alpine
    restart: always
    environment:
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
        # - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass tosya134526
    build:
      context: ~/project/Project_2_1_1/code for diagram 1/redis
    ports:
      - "6379:6379"
    networks:
      - project-network


  
networks:
  project-network:
    driver: bridge
    # external: true
