name: Deploy to Amazon ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

      - name: Build Docker image
        run: |
          pwd
          ls -la
          docker --version
          docker run hello-world
          # docker build -t my-app:latest .

      - name: Tag Docker image
        run: |
          # docker tag my-app:latest ${{ secrets.ECR_REPOSITORY_URI }}:latest

      - name: Push Docker image to Amazon ECR
        run: |
          # docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

        
